# Site settings
title: "Alfin William"
email: alfinwilliam@gmail.com
description: "My portfolio site with blog"
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: alfinwilliam
github_username:  alfinwilliam
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/alfin-william-91b20832/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: https://stackoverflow.com/users/4136843/duke-nukem
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/alfinwilliam\">Alfin William</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/alfinwilliam/alfinwilliam.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
